
services:

  mongodb:
    image: mongo:latest
    container_name: emp-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: Employees
    volumes:
      - emp_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - kafka_network

  employeeproducer.api:
    image: ${DOCKER_REGISTRY-}employeeproducerapi
    build:
      context: .
      dockerfile: Services/Producer/EmployeeProducer.API/Dockerfile
    networks:
      - kafka_network

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9.1
    # to survive the container restart
    tmpfs: "/zktmp"
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    networks:
      - kafka_network

  kafka1:
    image: docker.io/bitnami/kafka:3.7.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092,EXTERNAL://kafka1:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    # environment:
    #   - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    #   - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka1:9092,//172.21.128.1:9092,CONTROLLER://kafka1:9093,EXTERNAL://kafka1:9094
    #   - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092,//172.21.128.1:9092,EXTERNAL://kafka1:9094
    #   - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    #   - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - "kafka_data:/bitnami"
    networks:
      - kafka_network
       
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka1
    ports:
      - 9100:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997
    networks:
      - kafka_network

  conusmer.service:
    image: ${DOCKER_REGISTRY-}conusmerservice
    build:
      context: .
      dockerfile: Services/Consumer/Conusmer.Service/Dockerfile
    networks:
      - kafka_network
    depends_on:
      - mongodb

networks:
  kafka_network:
    driver: bridge

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  emp_data:
    driver: local

